name: dartnes
version: 0.0.1
description: A NES emulator written in Dart.
author: Matthew Brennan Jones <matthew.brennan.jones@gmail.com>
homepage: https://github.com/workhorsy/dartnes

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
